services:
  - type: web
    name: nestjs-api
    env: node
    buildCommand: pnpm install --no-frozen-lockfile && cd apps/api && pnpm prisma generate && pnpm prisma migrate deploy && pnpm nest build --webpack && ls -la dist
    startCommand: cd apps/api && pnpm deploy:start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true 