services:
  - type: web
    name: nestjs-api
    env: node
    buildCommand: |
      pnpm install --no-frozen-lockfile
      cd apps/api
      pnpm build
    startCommand: cd apps/api && pnpm start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true 